<?php

namespace Database\Seeders;

use Illuminate\Support\Str;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Laporans;
use App\Models\User;


class LaporanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $satgasPelaporUser1 = User::first();
        $satgasPelaporUser2 = User::where('role_id', 2)->first();

        Laporans::create([
            'uraian_singkat_masalah' => 'Laporan KDRT',
            'tanggal_jam_pengaduan' => now(),
            'no_telp_pelapor' => '1234567890',
            'no_telp_klien' => '1234567890',
            'nama_klien' => 'John Doe',
            'nama_pelapor' => 'Jane Smith',
            'validated' => false,
            'nik_pelapor' => Str::random(16), 
            'nik_klien' => Str::random(16), 
            'usia' => 30,
            'kategori_id' => 1, 
            'alamat_pelapor' => "adasdada",
            'alamat_klien' => "adasdada",
            "sumber_pengaduan_id" => random_int(1, 2), 
            'rt' => "1", 
            'rw' => "2", 
            'jenis_kelamin' => 'L', 
            'satgas_pelapor_id' => $satgasPelaporUser1->id, 
            'previous_satgas_id' => $satgasPelaporUser1->id, 
            'status_id' => 1,
            'token' => 'abc123',
            'situasi_keluarga' => 'hahahah',
            'kronologi_kejadian' => 'heheheheh',
            'harapan_klien_dan_keluarga' => 'hohohoho',
            'langkah_telah_dilakukan' => 'hahahah',
            'pendidikan_id' => 1, 
            'created_at' => now(),
            'updated_at' => now(),
            'deleted_at' => null,
        ]);
        Laporans::create([
            'uraian_singkat_masalah' => 'Laporan Pelecehan',
            'tanggal_jam_pengaduan' => now(),
            'no_telp_pelapor' => '1234567890',
            'no_telp_klien' => '1234567890',
            'nama_klien' => 'Haha ',
            'nama_pelapor' => 'Hihi',
            'validated' => false,
            'nik_pelapor' => Str::random(16), 
            'nik_klien' => Str::random(16), 
            'usia' => 20,
            'kategori_id' => 1, 
            'alamat_pelapor' => "adasdada",
            'alamat_klien' => "adasdada",
            "sumber_pengaduan_id" => random_int(1, 2), 
            'rt' => "1", 
            'rw' => "2", 
            'jenis_kelamin' => 'P', 
            'satgas_pelapor_id' => $satgasPelaporUser2->id, 
            'previous_satgas_id' => $satgasPelaporUser2->id, 
            'status_id' => 2,
            'token' => 'abc123',
            'situasi_keluarga' => 'hahahah',
            'kronologi_kejadian' => 'heheheheh',
            'harapan_klien_dan_keluarga' => 'hohohoho',
            'langkah_telah_dilakukan' => 'hahahah',
            'pendidikan_id' => 1, 
            'created_at' => now(),
            'updated_at' => now(),
            'deleted_at' => null,
        ]);
        Laporans::create([
            'uraian_singkat_masalah' => 'Laporan Kesuksesan',
            'tanggal_jam_pengaduan' => now(),
            'no_telp_pelapor' => '1234567890',
            'no_telp_klien' => '1234567890',
            'nama_klien' => 'Nyahaha ',
            'nama_pelapor' => 'Nyammy',
            'validated' => false,
            'nik_pelapor' => Str::random(16), 
            'nik_klien' => Str::random(16), 
            'usia' => 15,
            'kategori_id' => 2, 
            'alamat_pelapor' => "adasdada",
            'alamat_klien' => "adasdada",
            "sumber_pengaduan_id" => random_int(1, 2), 
            'rt' => "1", 
            'rw' => "2",
            'jenis_kelamin' => 'p', 
            'satgas_pelapor_id' => $satgasPelaporUser2->id, 
            'previous_satgas_id' => $satgasPelaporUser2->id, 
            'status_id' => 3,
            'token' => 'abc123',
            'situasi_keluarga' => 'hahahah',
            'kronologi_kejadian' => 'heheheheh',
            'harapan_klien_dan_keluarga' => 'hohohoho',
            'langkah_telah_dilakukan' => 'hahahah',
            'pendidikan_id' => 2, 
            'created_at' => now(),
            'updated_at' => now(),
            'deleted_at' => null,
        ]);
        Laporans::create([
            'uraian_singkat_masalah' => 'Laporan Kesuksesan',
            'tanggal_jam_pengaduan' => now(),
            'no_telp_pelapor' => '1234567890',
            'no_telp_klien' => '1234567890',
            'nama_klien' => 'Nyahaha ',
            'nama_pelapor' => 'Nyammy',
            'validated' => false,
            'nik_pelapor' => Str::random(16), 
            'nik_klien' => Str::random(16), 
            'usia' => 15,
            'kategori_id' => 2, 
            'alamat_pelapor' => "adasdada",
            'alamat_klien' => "adasdada",
            "sumber_pengaduan_id" => random_int(1, 2), 
            'rt' => "1", 
            'rw' => "2",
            'jenis_kelamin' => 'p', 
            'satgas_pelapor_id' => $satgasPelaporUser2->id, 
            'previous_satgas_id' => $satgasPelaporUser2->id, 
            'status_id' => 1,
            'situasi_keluarga' => 'hahahah',
            'kronologi_kejadian' => 'heheheheh',
            'harapan_klien_dan_keluarga' => 'hohohoho',
            'langkah_telah_dilakukan' => 'hahahah',
            'token' => 'abc123',
            'pendidikan_id' => 2, 
            'created_at' => now(),
            'updated_at' => now(),
            'deleted_at' => null,
        ]);
        Laporans::create([
            'uraian_singkat_masalah' => 'Laporan Kesuksesan',
            'tanggal_jam_pengaduan' => now(),
            'no_telp_pelapor' => '1234567890',
            'no_telp_klien' => '1234567890',
            'nama_klien' => 'Nyahaha ',
            'nama_pelapor' => 'Nyammy',
            'validated' => false,
            'nik_pelapor' => Str::random(16), 
            'nik_klien' => Str::random(16), 
            'usia' => 15,
            'situasi_keluarga' => 'hahahah',
            'kronologi_kejadian' => 'heheheheh',
            'harapan_klien_dan_keluarga' => 'hohohoho',
            'langkah_telah_dilakukan' => 'hahahah',
            'kategori_id' => 2, 
            'alamat_pelapor' => "adasdada",
            'alamat_klien' => "adasdada",
            "sumber_pengaduan_id" => random_int(1, 2), 
            'rt' => "1", 
            'rw' => "2",
            'jenis_kelamin' => 'p', 
            'satgas_pelapor_id' => $satgasPelaporUser2->id, 
            'previous_satgas_id' => $satgasPelaporUser2->id, 
            'status_id' => 1,
            'token' => 'abc123',
            'pendidikan_id' => 2, 
            'created_at' => now(),
            'updated_at' => now(),
            'deleted_at' => null,
        ]);
        Laporans::create([
            'uraian_singkat_masalah' => 'Laporan Kesuksesan',
            'tanggal_jam_pengaduan' => now(),
            'no_telp_pelapor' => '1234567890',
            'no_telp_klien' => '1234567890',
            'nama_klien' => 'Nyahaha ',
            'nama_pelapor' => 'Nyammy',
            'validated' => false,
            'nik_pelapor' => Str::random(16), 
            'nik_klien' => Str::random(16), 
            'usia' => 15,
            'situasi_keluarga' => 'hahahah',
            'kronologi_kejadian' => 'heheheheh',
            'harapan_klien_dan_keluarga' => 'hohohoho',
            'langkah_telah_dilakukan' => 'hahahah',
            'kategori_id' => 2, 
            'alamat_pelapor' => "adasdada",
            'alamat_klien' => "adasdada",
            "sumber_pengaduan_id" => random_int(1, 2), 
            'rt' => "1", 
            'rw' => "2",
            'jenis_kelamin' => 'p', 
            'satgas_pelapor_id' => $satgasPelaporUser2->id, 
            'previous_satgas_id' => $satgasPelaporUser2->id, 
            'status_id' => 4,
            'token' => 'abc123',
            'pendidikan_id' => 2, 
            'created_at' => now(),
            'updated_at' => now(),
            'deleted_at' => null,
        ]);
        Laporans::create([
            'uraian_singkat_masalah' => 'Laporan KDRT',
            'tanggal_jam_pengaduan' => now(),
            'no_telp_pelapor' => '1234567890',
            'no_telp_klien' => '1234567890',
            'nama_klien' => 'John Doe',
            'nama_pelapor' => 'Jane Smith',
            'validated' => false,
            'nik_pelapor' => Str::random(16), 
            'situasi_keluarga' => 'hahahah',
            'kronologi_kejadian' => 'heheheheh',
            'harapan_klien_dan_keluarga' => 'hohohoho',
            'langkah_telah_dilakukan' => 'hahahah',
            'nik_klien' => Str::random(16), 
            'usia' => 30,
            'kategori_id' => 1, 
            'alamat_pelapor' => "adasdada",
            'alamat_klien' => "adasdada",
            "sumber_pengaduan_id" => random_int(1, 2), 
            'rt' => "1", 
            'rw' => "2", 
            'jenis_kelamin' => 'L', 
            'satgas_pelapor_id' => $satgasPelaporUser2->id, 
            'previous_satgas_id' => $satgasPelaporUser2->id, 
            'status_id' => 1,
            'token' => 'abc123',
            'pendidikan_id' => 1, 
            'created_at' => now(),
            'updated_at' => now(),
            'deleted_at' => null,
        ]);
        Laporans::create([
            'uraian_singkat_masalah' => 'Laporan Pelecehan',
            'tanggal_jam_pengaduan' => now(),
            'no_telp_pelapor' => '1234567890',
            'no_telp_klien' => '1234567890',
            'situasi_keluarga' => 'hahahah',
            'kronologi_kejadian' => 'heheheheh',
            'harapan_klien_dan_keluarga' => 'hohohoho',
            'langkah_telah_dilakukan' => 'hahahah',
            'nama_klien' => 'Haha ',
            'nama_pelapor' => 'Hihi',
            'validated' => false,
            'nik_pelapor' => Str::random(16), 
            'nik_klien' => Str::random(16), 
            'usia' => 20,
            'kategori_id' => 1, 
            'alamat_pelapor' => "adasdada",
            'alamat_klien' => "adasdada",
            "sumber_pengaduan_id" => random_int(1, 2), 
            'rt' => "1", 
            'rw' => "2", 
            'jenis_kelamin' => 'P', 
            'satgas_pelapor_id' => $satgasPelaporUser2->id, 
            'previous_satgas_id' => $satgasPelaporUser2->id, 
            'status_id' => 2,
            'token' => 'abc123',
            'pendidikan_id' => 1, 
            'created_at' => now(),
            'updated_at' => now(),
            'deleted_at' => null,
        ]);
        Laporans::create([
            'uraian_singkat_masalah' => 'Laporan Kesuksesan',
            'tanggal_jam_pengaduan' => now(),
            'no_telp_pelapor' => '1234567890',
            'no_telp_klien' => '1234567890',
            'nama_klien' => 'Nyahaha ',
            'situasi_keluarga' => 'hahahah',
            'kronologi_kejadian' => 'heheheheh',
            'harapan_klien_dan_keluarga' => 'hohohoho',
            'langkah_telah_dilakukan' => 'hahahah',
            'nama_pelapor' => 'Nyammy',
            'validated' => false,
            'nik_pelapor' => Str::random(16), 
            'nik_klien' => Str::random(16), 
            'usia' => 15,
            'kategori_id' => 2, 
            'alamat_pelapor' => "adasdada",
            'alamat_klien' => "adasdada",
            "sumber_pengaduan_id" => random_int(1, 2), 
            'rt' => "1", 
            'rw' => "2",
            'jenis_kelamin' => 'p', 
            'satgas_pelapor_id' => $satgasPelaporUser2->id, 
            'previous_satgas_id' => $satgasPelaporUser2->id, 
            'status_id' => 3,
            'token' => 'abc123',
            'pendidikan_id' => 2, 
            'created_at' => now(),
            'updated_at' => now(),
            'deleted_at' => null,
        ]);
        Laporans::create([
            'uraian_singkat_masalah' => 'Laporan Kesuksesan',
            'tanggal_jam_pengaduan' => now(),
            'no_telp_pelapor' => '1234567890',
            'no_telp_klien' => '1234567890',
            'nama_klien' => 'Nyahaha ',
            'nama_pelapor' => 'Nyammy',
            'situasi_keluarga' => 'hahahah',
            'kronologi_kejadian' => 'heheheheh',
            'harapan_klien_dan_keluarga' => 'hohohoho',
            'langkah_telah_dilakukan' => 'hahahah',
            'validated' => false,
            'nik_pelapor' => Str::random(16), 
            'nik_klien' => Str::random(16), 
            'usia' => 15,
            'kategori_id' => 2, 
            'alamat_pelapor' => "adasdada",
            'alamat_klien' => "adasdada",
            "sumber_pengaduan_id" => random_int(1, 2), 
            'rt' => "1", 
            'rw' => "2",
            'jenis_kelamin' => 'p', 
            'satgas_pelapor_id' => $satgasPelaporUser2->id, 
            'previous_satgas_id' => $satgasPelaporUser2->id, 
            'status_id' => 1,
            'token' => 'abc123',
            'pendidikan_id' => 2, 
            'kelurahan_id' => 2,
            'created_at' => now(),
            'updated_at' => now(),
            'deleted_at' => null,
        ]);
        Laporans::create([
            'uraian_singkat_masalah' => 'Laporan Kesuksesan',
            'tanggal_jam_pengaduan' => now(),
            'no_telp_pelapor' => '1234567890',
            'situasi_keluarga' => 'hahahah',
            'kronologi_kejadian' => 'heheheheh',
            'harapan_klien_dan_keluarga' => 'hohohoho',
            'langkah_telah_dilakukan' => 'hahahah',
            'no_telp_klien' => '1234567890',
            'nama_klien' => 'Nyahaha ',
            'nama_pelapor' => 'Nyammy',
            'validated' => false,
            'nik_pelapor' => Str::random(16), 
            'nik_klien' => Str::random(16), 
            'usia' => 15,
            'kategori_id' => 2, 
            'alamat_pelapor' => "adasdada",
            'alamat_klien' => "adasdada",
            "sumber_pengaduan_id" => random_int(1, 2), 
            'rt' => "1", 
            'rw' => "2",
            'jenis_kelamin' => 'p', 
            'satgas_pelapor_id' => $satgasPelaporUser2->id, 
            'previous_satgas_id' => $satgasPelaporUser2->id, 
            'status_id' => 1,
            'token' => 'abc123',
            'pendidikan_id' => 2, 
            'created_at' => now(),
            'updated_at' => now(),
            'deleted_at' => null,
        ]);
        Laporans::create([
            'uraian_singkat_masalah' => 'Laporan Kesuksesan',
            'tanggal_jam_pengaduan' => now(),
            'no_telp_pelapor' => '1234567890',
            'no_telp_klien' => '1234567890',
            'situasi_keluarga' => 'hahahah',
            'kronologi_kejadian' => 'heheheheh',
            'harapan_klien_dan_keluarga' => 'hohohoho',
            'langkah_telah_dilakukan' => 'hahahah',
            'nama_klien' => 'Nyahaha ',
            'nama_pelapor' => 'Nyammy',
            'validated' => false,
            'nik_pelapor' => Str::random(16), 
            'nik_klien' => Str::random(16), 
            'usia' => 15,
            'kategori_id' => 2, 
            'alamat_pelapor' => "adasdada",
            'alamat_klien' => "adasdada",
            "sumber_pengaduan_id" => random_int(1, 2), 
            'rt' => "1", 
            'rw' => "2",
            'jenis_kelamin' => 'p', 
            'satgas_pelapor_id' => $satgasPelaporUser2->id, 
            'previous_satgas_id' => $satgasPelaporUser2->id, 
            'status_id' => 4,
            'token' => 'abc123',
            'pendidikan_id' => 2, 
            'created_at' => now(),
            'updated_at' => now(),
            'deleted_at' => null,
        ]);
        Laporans::create([
            'uraian_singkat_masalah' => 'Laporan KDRT',
            'tanggal_jam_pengaduan' => now(),
            'no_telp_pelapor' => '1234567890',
            'no_telp_klien' => '1234567890',
            'nama_klien' => 'John Doe',
            'nama_pelapor' => 'Jane Smith',
            'validated' => false,
            'nik_pelapor' => Str::random(16), 
            'nik_klien' => Str::random(16), 
            'situasi_keluarga' => 'hahahah',
            'kronologi_kejadian' => 'heheheheh',
            'harapan_klien_dan_keluarga' => 'hohohoho',
            'langkah_telah_dilakukan' => 'hahahah',
            'usia' => 30,
            'kategori_id' => 1, 
            'alamat_pelapor' => "adasdada",
            'alamat_klien' => "adasdada",
            "sumber_pengaduan_id" => random_int(1, 2), 
            'rt' => "1", 
            'rw' => "2", 
            'jenis_kelamin' => 'L', 
            'satgas_pelapor_id' => $satgasPelaporUser2->id, 
            'previous_satgas_id' => $satgasPelaporUser2->id, 
            'status_id' => 1,
            'token' => 'abc123',
            'pendidikan_id' => 1, 
            'created_at' => now(),
            'updated_at' => now(),
            'deleted_at' => null,
        ]);
        Laporans::create([
            'uraian_singkat_masalah' => 'Laporan Pelecehan',
            'tanggal_jam_pengaduan' => now(),
            'no_telp_pelapor' => '1234567890',
            'no_telp_klien' => '1234567890',
            'nama_klien' => 'Haha ',
            'nama_pelapor' => 'Hihi',
            'validated' => false,
            'nik_pelapor' => Str::random(16), 
            'situasi_keluarga' => 'hahahah',
            'kronologi_kejadian' => 'heheheheh',
            'harapan_klien_dan_keluarga' => 'hohohoho',
            'langkah_telah_dilakukan' => 'hahahah',
            'nik_klien' => Str::random(16), 
            'usia' => 20,
            'kategori_id' => 1, 
            'alamat_pelapor' => "adasdada",
            'alamat_klien' => "adasdada",
            "sumber_pengaduan_id" => random_int(1, 2), 
            'rt' => "1", 
            'rw' => "2", 
            'jenis_kelamin' => 'P', 
            'satgas_pelapor_id' => $satgasPelaporUser2->id, 
            'previous_satgas_id' => $satgasPelaporUser2->id, 
            'status_id' => 2,
            'token' => 'abc123',
            'pendidikan_id' => 1, 
            'created_at' => now(),
            'updated_at' => now(),
            'deleted_at' => null,
        ]);
        Laporans::create([
            'uraian_singkat_masalah' => 'Laporan Kesuksesan',
            'tanggal_jam_pengaduan' => now(),
            'no_telp_pelapor' => '1234567890',
            'no_telp_klien' => '1234567890',
            'situasi_keluarga' => 'hahahah',
            'kronologi_kejadian' => 'heheheheh',
            'harapan_klien_dan_keluarga' => 'hohohoho',
            'langkah_telah_dilakukan' => 'hahahah',
            'nama_klien' => 'Nyahaha ',
            'nama_pelapor' => 'Nyammy',
            'validated' => false,
            'nik_pelapor' => Str::random(16), 
            'nik_klien' => Str::random(16), 
            'usia' => 15,
            'kategori_id' => 2, 
            'alamat_pelapor' => "adasdada",
            'alamat_klien' => "adasdada",
            "sumber_pengaduan_id" => random_int(1, 2), 
            'rt' => "1", 
            'rw' => "2",
            'jenis_kelamin' => 'p', 
            'satgas_pelapor_id' => $satgasPelaporUser2->id, 
            'previous_satgas_id' => $satgasPelaporUser2->id, 
            'status_id' => 3,
            'token' => 'abc123',
            'pendidikan_id' => 2, 
            'created_at' => now(),
            'updated_at' => now(),
            'deleted_at' => null,
        ]);
        Laporans::create([
            'uraian_singkat_masalah' => 'Laporan Kesuksesan',
            'tanggal_jam_pengaduan' => now(),
            'no_telp_pelapor' => '1234567890',
            'no_telp_klien' => '1234567890',
            'nama_klien' => 'Nyahaha ',
            'nama_pelapor' => 'Nyammy',
            'situasi_keluarga' => 'hahahah',
            'kronologi_kejadian' => 'heheheheh',
            'harapan_klien_dan_keluarga' => 'hohohoho',
            'langkah_telah_dilakukan' => 'hahahah',
            'validated' => false,
            'nik_pelapor' => Str::random(16), 
            'nik_klien' => Str::random(16), 
            'usia' => 15,
            'kategori_id' => 2, 
            'alamat_pelapor' => "adasdada",
            'alamat_klien' => "adasdada",
            "sumber_pengaduan_id" => random_int(1, 2), 
            'rt' => "1", 
            'rw' => "2",
            'jenis_kelamin' => 'p', 
            'satgas_pelapor_id' => $satgasPelaporUser2->id, 
            'previous_satgas_id' => $satgasPelaporUser2->id, 
            'status_id' => 1,
            'token' => 'abc123',
            'pendidikan_id' => 2, 
            'created_at' => now(),
            'updated_at' => now(),
            'deleted_at' => null,
        ]);
        Laporans::create([
            'uraian_singkat_masalah' => 'Laporan Kesuksesan',
            'tanggal_jam_pengaduan' => now(),
            'no_telp_pelapor' => '1234567890',
            'no_telp_klien' => '1234567890',
            'nama_klien' => 'Nyahaha ',
            'nama_pelapor' => 'Nyammy',
            'validated' => false,
            'nik_pelapor' => Str::random(16), 
            'situasi_keluarga' => 'hahahah',
            'kronologi_kejadian' => 'heheheheh',
            'harapan_klien_dan_keluarga' => 'hohohoho',
            'langkah_telah_dilakukan' => 'hahahah',
            'nik_klien' => Str::random(16), 
            'usia' => 15,
            'kategori_id' => 2, 
            'alamat_pelapor' => "adasdada",
            'alamat_klien' => "adasdada",
            "sumber_pengaduan_id" => random_int(1, 2), 
            'rt' => "1", 
            'rw' => "2",
            'jenis_kelamin' => 'p', 
            'satgas_pelapor_id' => $satgasPelaporUser2->id, 
            'previous_satgas_id' => $satgasPelaporUser2->id, 
            'status_id' => 1,
            'token' => 'abc123',
            'pendidikan_id' => 2, 
            'created_at' => now(),
            'updated_at' => now(),
            'deleted_at' => null,
        ]);
        Laporans::create([
            'uraian_singkat_masalah' => 'Laporan Kesuksesan',
            'tanggal_jam_pengaduan' => now(),
            'no_telp_pelapor' => '1234567890',
            'no_telp_klien' => '1234567890',
            'nama_klien' => 'Nyahaha ',
            'nama_pelapor' => 'Nyammy',
            'situasi_keluarga' => 'hahahah',
            'kronologi_kejadian' => 'heheheheh',
            'harapan_klien_dan_keluarga' => 'hohohoho',
            'langkah_telah_dilakukan' => 'hahahah',
            'validated' => false,
            'nik_pelapor' => Str::random(16), 
            'nik_klien' => Str::random(16), 
            'usia' => 15,
            'kategori_id' => 2, 
            'alamat_pelapor' => "adasdada",
            'alamat_klien' => "adasdada",
            "sumber_pengaduan_id" => random_int(1, 2), 
            'rt' => "1", 
            'rw' => "2",
            'jenis_kelamin' => 'p', 
            'satgas_pelapor_id' => $satgasPelaporUser2->id, 
            'previous_satgas_id' => $satgasPelaporUser2->id, 
            'status_id' => 4,
            'token' => 'abc123',
            'pendidikan_id' => 2, 
            'created_at' => now(),
            'updated_at' => now(),
            'deleted_at' => null,
        ]);
        
    }
}
